// frontend/src/components/app/FileStation.tsx
import React from "react"
import WindowLayout from "../layout/WindowLayout"
import WindowContent from "../layout/WindowContent"
import SidebarLayout from "../layout/SidebarLayout"
import SidebarContent from "../layout/SidebarContent"
import TreeView from "../widget/TreeView"
import ToolbarLayout, { ToolbarCell } from "../layout/ToolbarLayout"
import { ButtonIcon, ButtonText } from "../widget/Button"
import Breadcrumb from "../widget/Breadcrumb"
import Dropdown from "../widget/Dropdown"
import IconFolder from "../../assets/icon/svg/icon-folder.svg"
import TreeViewData from "../../tree-view.json"
import BreadcrumbData from "../../breadcrumb.json"
import DropdownData from "../../dropdown.json"

export default class FileStation extends
  React.Component {
  render(): React.ReactNode {
    return <WindowLayout
      icon={IconFolder}
      title="File Staion"
    >
      <SidebarLayout>
        <TreeView node={TreeViewData} />
      </SidebarLayout>
      <SidebarContent>
        <ToolbarLayout>
          <ToolbarCell>
            <ButtonIcon icon="ic-arrow-back"></ButtonIcon>
            <ButtonIcon icon="ic-arrow-forward"></ButtonIcon>
          </ToolbarCell>
          <ToolbarCell>
            <ButtonIcon icon="ic-refresh"></ButtonIcon>
          </ToolbarCell>
          <ToolbarCell className="stretch">
            <Breadcrumb lists={BreadcrumbData} />
          </ToolbarCell>
          <ToolbarCell>
            <input
              type="text"
              className="toolbar-input"
              placeholder="Search" />
          </ToolbarCell>
        </ToolbarLayout>
        <ToolbarLayout>
          <ToolbarCell>
            <Dropdown id="create-dropdown" lists={DropdownData} label="Create" />
          </ToolbarCell>
          <ToolbarCell>
            <Dropdown id="upload-dropdown" lists={DropdownData} label="Upload" />
          </ToolbarCell>
          <ToolbarCell>
            <Dropdown id="action-dropdown" lists={DropdownData} label="Action" />
          </ToolbarCell>
          <ToolbarCell>
            <Dropdown id="tools-dropdown" lists={DropdownData} label="Tools" />
          </ToolbarCell>
          <ToolbarCell>
            <ButtonText>Settings</ButtonText>
          </ToolbarCell>
        </ToolbarLayout>
        <WindowContent>
          {Array(100).fill(undefined).map((value, index) => {
            return <p>Line index {index}</p>
          })}
        </WindowContent>
      </SidebarContent>
    </WindowLayout>
  }
}

// frontend/src/components/app/FileStation.vue
<script>
  import Window from "../layout/Window.vue"
  import WindowContent from "../layout/WindowContent.vue"
  import SidebarLayout from "../layout/SidebarLayout.vue"
  import SidebarContent from "../layout/SidebarContent.vue"
  import TreeView from "../widget/TreeView.vue"
  import Toolbar from "../layout/Toolbar.vue"
  import ToolbarCell from "../widget/ToolbarCell.vue"
  import Breadcrumb from "../widget/Breadcrumb.vue"
  import Dropdown from "../widget/Dropdown.vue"
  import ButtonText from "../widget/ButtonText.vue"
  import ButtonIcon from "../widget/ButtonIcon.vue"

  const breadcrumbData = [
    "Home", "Directory", "File"
  ]

  const dropdownData = [
    { title: "Create directory", icon: "ic-folder", disable: false },
    { title: "About current directory", disable: true, divider: true },
    { title: "Create shared folder", icon: "ic-search" },
    { title: "Mount", disable: false, icon: "ic-about", sub: [
      { title: "Mount disk" },
      { title: "Mount network" },
      { title: "Mount domain", disable: true }
    ]}
  ]

  export default {
    name: "FileStation",

    data() {
      return { breadcrumbData, dropdownData }
    },

    components: { Window, WindowContent, SidebarContent, SidebarLayout,
      TreeView, Toolbar, ToolbarCell, Breadcrumb, Dropdown, ButtonText,
      ButtonIcon }
  }
</script>

<template>
  <Window title="FileStation"
    icon="/icon/svg/icon-folder.svg"
    enableSidebar
  >
    <SidebarLayout>
      <TreeView></TreeView>
    </SidebarLayout>
    <SidebarContent>
      <Toolbar>
        <ToolbarCell>
          <ButtonIcon icon="ic-arrow-back"></ButtonIcon>
          <ButtonIcon icon="ic-arrow-forward"></ButtonIcon>
        </ToolbarCell>
        <ToolbarCell>
          <ButtonIcon icon="ic-refresh"></ButtonIcon>
        </ToolbarCell>
        <ToolbarCell class="stretch">
          <Breadcrumb v-bind:lists="breadcrumbData"/>
        </ToolbarCell>
        <ToolbarCell>
          <input type="text" value="" class="toolbar-input" placeholder="Search"/>
        </ToolbarCell>
      </Toolbar>
      <Toolbar>
        <ToolbarCell>
          <Dropdown id="create-dropdown" v-bind:lists="dropdownData">
            <span>Create</span>
          </Dropdown>
        </ToolbarCell>
        <ToolbarCell>
          <Dropdown id="upload-dropdown" v-bind:lists="dropdownData">
            <span>Upload</span>
          </Dropdown>
        </ToolbarCell>
        <ToolbarCell>
          <Dropdown id="action-dropdown" v-bind:lists="dropdownData">
            <span>Action</span>
          </Dropdown>
        </ToolbarCell>
        <ToolbarCell>
          <Dropdown id="tool-dropdown" v-bind:lists="dropdownData">
            <span>Tools</span>
          </Dropdown>
        </ToolbarCell>
        <ToolbarCell>
          <ButtonText>Settings</ButtonText>
        </ToolbarCell>
      </Toolbar>
      <WindowContent>
        <p v-for="index in 100" v-bind:key="index">
          Line index {{ index }}
        </p>
      </WindowContent>
    </SidebarContent>
  </Window>
</template>
