// frontend/src/components/widget/Breadcrumb.tsx
import React from "react"
import classNames from "classnames"

type BreadcrumbProps = {
  lists: Array<string>
}

const Breadcrumb: React.FC<BreadcrumbProps &
  React.HTMLAttributes<HTMLUListElement>> =
  (props) => {
    return <ul className={classNames("breadcrumb", props.className)}>
      {props.lists.map((entry, index) => {
        return <li className="breadcrumb-item" key={index}>
          <span className="breadcrumb-label">{entry}</span>
        </li>
      })}
    </ul>
  }
export default Breadcrumb

// frontend/src/components/widget/Breadcrumb.vue
<script>
  import BreadcrumbItem from "../item/BreadcrumbItem.vue"

  export default {
    name: "Breadcrumb",
    props: {
      lists: Array
    },

    components: { BreadcrumbItem }
  }
</script>

<template>
  <ul class="breadcrumb">
    <BreadcrumbItem
      v-for="(item, index) in lists"
      v-bind:key="index"
      v-bind:item="item"/>
  </ul>
</template>
