// frontend/src/components/widget/Dropdown.tsx
import React, { useState, useEffect } from "react"
import classNames from "classnames"

export interface IDropdownEntryItem {
  name: string
  icon?: string
  disabled?: boolean
  divider?: boolean
  subs?: Array<IDropdownSubEntryItem>
}

export interface IDropdownSubEntryItem {
  name: string
  icon?: string
}

type OnCloseCallback = (entry: IDropdownEntryItem, index: number) => any
type DropdownEntryProps = {
  index: number
  entry: IDropdownEntryItem
  onClose: OnCloseCallback
}
type DropdownProps = {
  id: string
  label?: string
  lists?: Array<IDropdownEntryItem>
}

const DropdownEntry: React.FC<DropdownEntryProps &
  React.HTMLAttributes<HTMLDivElement>> =
  (props) => {
    return <div
      className={classNames("dropdown-item", props.className)}
      onClick={props.onClose.bind(this, props.entry, props.index)}
    >{props.children}</div>
  }

const Dropdown: React.FC<DropdownProps &
  React.HTMLAttributes<HTMLDivElement>> = (props) => {
    const [isOpen, setOpen] = useState(false)

    function checkClickOn(event: any) {
      if (!document.getElementById(props.id)?.contains(event.target))
        setOpen(false)
    }

    function toggle() {
      setOpen(!isOpen)
    }

    function onClickEntryItem(entry: IDropdownEntryItem, index: number) {
      if (!entry.subs)
        setOpen(false)
    }

    function onClickSubEntryItem(event: any,
      entry: IDropdownEntryItem, index: number,
      subEntry: IDropdownSubEntryItem, subIndex: number) {
      setOpen(false)
      event.stopPropagation()
      event.preventDefault()
    }

    useEffect(() => {
      window.addEventListener("click", checkClickOn)
      return () => window.removeEventListener("click", checkClickOn)
    })

    return <div id={props.id} className={classNames("dropdown",
      props.className)}
    >
      <button
        onClick={toggle}
        className={classNames({
          "btn": true, "btn-dropdown": true,
          "btn-dropdown-arrow": true, "isActive": isOpen
        })}
      >
        {props.label ? <span>{props.label}</span> : props.children}
      </button>

      {isOpen && <div className="dropdown-list">
        {props.lists?.map((entry, index) => {
          return <DropdownEntry
            key={index}
            index={index}
            entry={entry}
            onClose={onClickEntryItem}
            className={classNames({
              "disabled": entry.disabled,
              "divider": entry.divider,
              "sub": entry.subs
            })}
          >
            <span className={classNames("dropdown-icon", "icomoon",
              !entry.icon ? "ic-zero invisible" : entry.icon)}></span>
            <span className="dropdown-label">{entry.name}</span>
            {entry.subs && <div className="dropdown-sub">
              {entry.subs.map((subEntry, subIndex) => {
                return <div
                  key={subIndex}
                  className="dropdown-sub-item"
                  onClick={(event) => onClickSubEntryItem(event,
                    entry, index, subEntry, subIndex)}
                >
                  <span className="dropdown-label">{subEntry.name}</span>
                </div>
              })}
            </div>}
          </DropdownEntry>
        })}
      </div>}
    </div>
  }

export default Dropdown

// frontend/src/components/dropdown/Dropdown.vue
<script>
  import DropdownItem from "./DropdownItem"

  export default {
    name: "Dropdown",
    components: { DropdownItem },
    props: {
      id: { type: String, required: true },
      lists: { type: Array, default: () => [] }
    },

    created() {
      window.addEventListener("click", this.checkClickOn)
    },

    beforeUnmount() {
      window.removeEventListener("click", this.checkClickOn)
    },

    data() {
      return { isOpen: false }
    },

    methods: {
      clickItem(item, index) {
        if (!item.sub) {
          this.isOpen = false
        }
      },

      clickSubItem(item, index, subItem, subIndex) {
        this.isOpen = false
      },

      checkClickOn(event) {
        if (!document.getElementById(this.id).contains(event.target))
          this.isOpen = false
      }
    }
  }
</script>

<template>
  <div v-bind:id="id" class="dropdown">
    <button
      class="dropdown-button"
      v-on:click="isOpen = !isOpen"
      v-bind:class="{ isActive: isOpen }"
    >
      <slot/>
    </button>
    <div class="dropdown-list" v-if="isOpen">
      <DropdownItem
        v-for="(item, index) in lists"
        v-bind:key="index"
        v-bind:index="index"
        v-bind:item="item"
        v-bind:close="clickItem"
        v-bind:class="{
          disabled: item.disable,
          divider: item.divider,
          sub: item.sub
        }"
      >
        <span class="dropdown-icon icomoon ic-folder" v-if="item.icon"></span>
        <span class="dropdown-icon icomoon ic-zero invisible" v-else></span>
        <span class="dropdown-label">{{ item.title }}</span>

        <div v-if="item.sub" class="dropdown-sub">
          <div
            class="dropdown-sub-item"
            v-for="(subItem, subIndex) in item.sub"
            v-bind:key="subIndex"
            v-on:click.stop.prevent="clickSubItem(item, index, subItem, subIndex)"
          >
            <span class="dropdown-label">{{ subItem.title }}</span>
          </div>
        </div>
      </DropdownItem>
    </div>
  </div>
</template>
