// frontend/src/components/layout/WindowLayout.tsx
import React from "react"
import classNames from "classnames"

type WindowLayoutProps = {
  icon?: string
  title: string
  isButtonHelp?: boolean
  isButtonMinimize?: boolean
  isButtonRestore?: boolean
  isButtonClose?: boolean
}

const WindowLayout: React.FC<WindowLayoutProps &
  React.HTMLAttributes<HTMLDivElement>> =
  (props) => {
    return <div className={classNames("window", props.className)}>
      <div className="window-titlebars">
        <div className="window-titlebars-title">
          {props.icon && <img src={props.icon}
            className="window-titlebars-icon"
            alt={props.title} />}
          <span className="window-titlebars-label">{props.title}</span>
        </div>
        <div className="window-titlebars-button">
          {props.isButtonHelp && <button
            className="window-titlebars-button-item icomoon ic-about"
            data-action="help"></button>}

          {(props.isButtonMinimize || true) && <button
            className="window-titlebars-button-item icomoon ic-window-minimize"
            data-action="minimize"></button>}

          {(props.isButtonRestore || true) && <button
            className="window-titlebars-button-item icomoon ic-window-restore"
            data-action="restore"></button>}

          {(props.isButtonClose || true) && <button
            className="window-titlebars-button-item icomoon ic-window-close"
            data-action="close"></button>}
        </div>
      </div>
      <div className="window-container window-sidebar-container">
        {props.children}
      </div>
    </div>
  }

export default WindowLayout

// frontend/src/components/layout/WindowLayout.vue
<script lang="ts">
  import { Options, Vue } from "vue-class-component"

  @Options({
    props: {
      icon: { type: String, default: "" },
      title: { type: String, required: true },
      actionHelp: { type: Boolean },
      actionMinimize: { type: Boolean, default: true },
      actionRestore: { type: Boolean, default: true },
      actionClose: { type: Boolean, default: true },
      enableSidebar: { type: Boolean }
    }
  })

  export default class WindowLayout extends Vue {
    public icon?: string
    public title?: string
    public actionHelp?: boolean
    public actionMinimize?: boolean
    public actionRestore?: boolean
    public actionClose?: boolean
    public enableSidebar?: boolean
  }
</script>

<template>
  <div class="window">
    <div class="window-titlebars">
      <div class="window-titlebars-title">
        <img v-bind:src="icon"
            class="window-titlebars-icon"
            v-bind:alt="title"/>
        <span class="window-titlebars-label">{{ title }}</span>
      </div>
      <div class="window-titlebars-button">
        <button
          v-if="actionHelp"
          class="window-titlebars-button-item icomoon ic-about"
          data-action="help"
        ></button>
        <button
          v-if="actionMinimize"
          class="window-titlebars-button-item icomoon ic-window-minimize"
          data-action="minimize"
        ></button>
        <button
          v-if="actionRestore"
          class="window-titlebars-button-item icomoon ic-window-restore"
          data-action="restore"
        ></button>
        <button
          v-if="actionClose"
          class="window-titlebars-button-item icomoon ic-window-close"
          data-action="close"
        ></button>
      </div>
    </div>
    <div class="window-container window-sidebar-container">
      <slot/>
    </div>
  </div>
</template>
