// frontend/src/components/App.tsx
import React from "react"
import Navigation from "./widget/Navigation"
import DesktopGrid from "./app/DesktopGrid"
import FileStation from "./app/FileStation"
import "../sass/app.scss"

interface IAppState {
  windowWidth: number
  windowHeight: number
}

export default class App extends React.Component<{}, IAppState> {
  constructor(props: any) {
    super(props);
    this.state = {
      windowWidth: this.clientWidth(),
      windowHeight: this.clientHeight()
    }
  }

  clientWidth(): number { return document.documentElement.clientWidth }
  clientHeight(): number { return document.documentElement.clientHeight }

  dispatchDimensions(): void {
    this.setState({
      windowWidth: this.clientWidth(),
      windowHeight: this.clientHeight()
    })
  }

  componentDidMount(): void {
    window.addEventListener("resize", this
      .dispatchDimensions.bind(this));
  }

  componentWillUnmount(): void {
    window.removeEventListener("resize", this
      .dispatchDimensions);
  }

  render(): React.ReactNode {
    return <div
      className="bg-cover"
      style={{ height: this.state.windowHeight + "px" }}
    >
      <Navigation/>
      <div className="bg-overlay"></div>
      <div className="container-wrapper">
        <DesktopGrid/>
        <FileStation/>
      </div>
    </div>
  }
}

// backup/frontend-old/src/App.vue
<style lang="scss">
  @import "@/sass/app.scss";
</style>

<script>
  import DesktopGrid from "./components/DesktopGrid.vue"
  import Navigation from "./components/Navigation.vue"
  import FileStation from "./components/FileStation.vue"
  import { mapState } from "vuex"

  const clientWidth = () => document.documentElement.clientWidth
  const clientHeight = () => document.documentElement.clientHeight

  export default {
      name: "App",

      components: {
          DesktopGrid, Navigation, FileStation
      },

      computed: {
        ...mapState({
          isAuthentic: state => state.authenticate.isAuthentic
        })
      },

      data: () => {
          return {
              windowWidth: clientWidth(),
              windowHeight: clientHeight()
          }
      },

      methods: {
          dispatchDimensions() {
              this.windowWidth = clientWidth();
              this.windowHeight = clientHeight();
          }
      },

      mounted() {
          window.addEventListener("resize", this.dispatchDimensions)
      },

      unmounted() {
          window.removeEventListener("resize", this.dispatchDimensions);
      }
  }
</script>

<template>
  <div class="bg-cover" v-bind:style="{ height: windowHeight + 'px' }">
    <div class="bg-overlay"></div>
    <Navigation />
    <div class="container-wrapper">
      <DesktopGrid v-if="isAuthentic"/>
      <FileStation v-if="isAuthentic"/>
    </div>
  </div>
</template>
